# Generated by Django 3.2.3 on 2022-01-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
