# Generated by Django 3.2.3 on 2022-01-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220125_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['my_order'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lesson'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='my_order',
        ),
        migrations.AddField(
            model_name='lesson',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
