# Generated by Django 3.2.3 on 2022-01-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20220125_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['sortable_inline_order'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lesson'},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='my_order',
            new_name='sortable_inline_order',
        ),
    ]
