# Generated by Django 3.2.3 on 2022-01-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_docs_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'ordering': ['sortable_inline_order'], 'verbose_name': 'Docs', 'verbose_name_plural': 'Docs'},
        ),
        migrations.AddField(
            model_name='docs',
            name='sortable_inline_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
