# Generated by Django 3.2.3 on 2022-01-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20220125_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
