# Generated by Django 3.2.3 on 2022-01-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_docs_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
