# Generated by Django 3.1.7 on 2021-03-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='topic',
        ),
        migrations.AddField(
            model_name='material',
            name='topics',
            field=models.ManyToManyField(to='material.Topic'),
        ),
    ]
