# Generated by Django 3.1.7 on 2021-03-27 18:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import material.models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20210327_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='video',
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to=material.models.upload_dir_path)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('topics', models.ManyToManyField(to='material.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('url_exercise', models.URLField(blank=True, null=True)),
                ('url_correction', models.URLField(blank=True, null=True)),
                ('from_date', models.DateField(default=datetime.datetime.now)),
                ('correction_format', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='material.materialtype')),
                ('exercise_format', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='material.materialtype')),
                ('topics', models.ManyToManyField(to='material.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
