# Generated by Django 3.2.3 on 2021-05-24 16:07

from django.db import migrations, models
import material.models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_material_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to=material.models.upload_video_path),
        ),
    ]
