# Generated by Django 3.2.3 on 2021-05-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_material_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='subcategory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.subcategory'),
        ),
    ]
