# Generated by Django 3.2.3 on 2022-01-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_auto_20210524_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
    ]
